CREATE DATABASE QLHOCPHAN

CREATE TABLE KHOA
(
MAKHOA NVARCHAR(10) NOT NULL PRIMARY KEY,
TENKHOA NVARCHAR(50)
)

CREATE TABLE BOMON
(
MABM NVARCHAR(10) NOT NULL PRIMARY KEY,
TENBM NVARCHAR(50),
MAKHOA NVARCHAR(10) NOT NULL
)

ALTER TABLE BOMON
ADD CONSTRAINT FR_BM_K_MAKHOA
FOREIGN KEY (MAKHOA)
REFERENCES KHOA (MAKHOA)

CREATE TABLE GIANGVIEN
(
MAGV NVARCHAR(10) NOT NULL PRIMARY KEY,
HOTEN NVARCHAR(50),
MABM NVARCHAR(10) NOT NULL
)

ALTER TABLE GIANGVIEN
ADD CONSTRAINT FR_GV_BM_MABM
FOREIGN KEY (MABM)
REFERENCES BOMON (MABM)

CREATE TABLE HOCPHAN
(
MAHP NVARCHAR(10) NOT NULL PRIMARY KEY,
TENHP NVARCHAR(50),
MABM NVARCHAR(10) NOT NULL
)

ALTER TABLE HOCPHAN
ADD CONSTRAINT FR_HP_BM_MABM
FOREIGN KEY (MABM)
REFERENCES BOMON (MABM)

 
  
